
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
spec:
     storageClassName: {{ .Values.mysql.StorageClassName }}
     accessModes: 
        - ReadWriteOnce
     capacity:
           storage: {{ .Values.mysql.volCapacity }}
     hostPath: 
        path: "/mydata"
       
