apiVersion: v1
kind: PersistentVolume
metadata:
    name: wordpress-pv
spec:
     storageClassName: {{ .Values.wordpress.StorageClassName }}        
     accessModes: 
        - ReadWriteOnce
     capacity:
           storage: {{ .Values.wordpress.volCapacity}}  
     hostPath: 
        path: "/mydata"