apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: {{ .Values.wordpress.containerPort}}
  selector:
    app: wordpress
    tier: mysql
  type: {{ .Values.wordpress.type }}
